# Generated by Django 5.0.7 on 2025-09-13 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='العميل')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app.invoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_returned', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoiceitem', verbose_name='العنصر الأصلي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='المنتج')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.return', verbose_name='المرتجع')),
            ],
            options={
                'verbose_name': 'عنصر المرتجع',
                'verbose_name_plural': 'عناصر المرتجع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم السبب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سبب المرتجع',
                'verbose_name_plural': 'أسباب المرتجع',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.returnreason', verbose_name='سبب المرتجع'),
        ),
    ]
