# Generated by Django 5.0.7 on 2025-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, help_text='القياس (اختياري)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('piece', 'عدد'), ('meter', 'متر'), ('kg', 'كيلو'), ('liter', 'لتر'), ('box', 'صندوق'), ('pack', 'عبوة'), ('roll', 'لفة'), ('sheet', 'ورقة'), ('other', 'أخرى')], default='piece', help_text='وحدة القياس', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قيمة الوحدة', max_digits=10, null=True),
        ),
    ]
