# Generated by Django 5.0.7 on 2025-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_return_returnitem_returnreason_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='reason',
        ),
        migrations.DeleteModel(
            name='ReturnReason',
        ),
    ]
