# Generated by Django 5.0.7 on 2025-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_value',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='وصف المنتج (اختياري)', null=True),
        ),
    ]
