# Generated by Django 5.0.7 on 2025-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر التكلفة', max_digits=12, null=True, verbose_name='سعر التكلفة'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر البيع بالمفرق', max_digits=12, null=True, verbose_name='سعر البيع بالمفرق'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سعر البيع بالجملة', max_digits=12, null=True, verbose_name='سعر البيع بالجملة'),
        ),
    ]
