# Generated by Django 5.0.7 on 2025-09-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_cost_price_product_retail_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_webhook_url', models.URLField(verbose_name='رابط الواتساب')),
                ('gemini_api_key', models.CharField(max_length=500, verbose_name='مفتاح Gemini API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('max_conversation_history', models.IntegerField(default=20, verbose_name='عدد الرسائل المحفوظة')),
                ('confirmation_required', models.BooleanField(default=True, verbose_name='يتطلب تأكيد للعمليات الحساسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات الوكيل',
                'verbose_name_plural': 'إعدادات الوكيل',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('response', models.TextField(verbose_name='الرد')),
                ('tool_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='الأداة المستخدمة')),
                ('is_confirmation', models.BooleanField(default=False, verbose_name='رسالة تأكيد')),
                ('confirmation_data', models.JSONField(blank=True, null=True, verbose_name='بيانات التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-created_at'],
            },
        ),
    ]
