# Generated by Django 5.0.7 on 2025-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_cost_price_product_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='total_invoiced',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='إجمالي الفواتير'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='total_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='إجمالي المدفوع'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='total_returns',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='إجمالي المرتجعات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_at_add',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='السعر عند الإضافة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='سعر التكلفة', max_digits=12, null=True, verbose_name='سعر التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='سعر البيع بالمفرق', max_digits=12, null=True, verbose_name='سعر البيع بالمفرق'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='سعر البيع بالجملة', max_digits=12, null=True, verbose_name='سعر البيع بالجملة'),
        ),
        migrations.AlterField(
            model_name='return',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='line_total',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='المجموع'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='qty_returned',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المرتجعة'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='سعر الوحدة'),
        ),
    ]
