# Generated by Django 5.0.7 on 2025-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_agentsettings_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='custom_system_message',
            field=models.TextField(blank=True, null=True, verbose_name='النظام المسج المخصص'),
        ),
    ]
