# Generated by Django 5.0.7 on 2025-09-20 21:10

import django.db.models.deletion
from django.db import migrations, models


def create_company_profiles(apps, schema_editor):
    Company = apps.get_model('app', 'Company')
    CompanyProfile = apps.get_model('app', 'CompanyProfile')
    for company in Company.objects.all():
        CompanyProfile.objects.get_or_create(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_customerbalance_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="مؤرشف"),
        ),
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="مؤرشف"),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="شعار الشركة",
                    ),
                ),
                (
                    "return_policy",
                    models.TextField(blank=True, verbose_name="سياسة الإرجاع"),
                ),
                (
                    "payment_policy",
                    models.TextField(blank=True, verbose_name="سياسة الدفع"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="app.company",
                        verbose_name="الشركة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف الشركة",
                "verbose_name_plural": "ملفات الشركات",
            },
        ),
        migrations.RunPython(create_company_profiles, migrations.RunPython.noop),
    ]
