# Generated by Django 5.0.7 on 2025-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_agentsettings_custom_system_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوكيل')),
                ('whatsapp_webhook_url', models.URLField(max_length=500, verbose_name='رابط الويب هوك')),
                ('gemini_api_key', models.CharField(max_length=200, verbose_name='مفتاح Gemini API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, verbose_name='وكيل رئيسي')),
                ('max_conversation_history', models.IntegerField(default=20, verbose_name='حد المحادثة')),
                ('confirmation_required', models.BooleanField(default=True, verbose_name='يتطلب تأكيد')),
                ('custom_system_message', models.TextField(blank=True, verbose_name='رسالة النظام المخصصة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الوكيل الذكي',
                'verbose_name_plural': 'الوكلاء الذكيون',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
