# Generated by Django 5.0.7 on 2025-09-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المفتاح')),
                ('key', models.CharField(max_length=500, verbose_name='مفتاح API')),
                ('provider', models.CharField(default='gemini', max_length=50, verbose_name='مزود الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, verbose_name='مفتاح رئيسي')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('max_requests_per_day', models.IntegerField(default=1000, verbose_name='الحد الأقصى للطلبات يومياً')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مفتاح API',
                'verbose_name_plural': 'مفاتيح API',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
